#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json

data_b = dict()
data_b['buildings'] = []

# Dům u kameného zvonu
data_b['buildings'].append({
    'id': '0',
    'name': 'Dům u kameného zvonu',
    'path': 'C:\\Users\\Sefci\\Documents\\_FIT\\_Bakalarka\\data_staromak\\b1',
    'latitude':   '50.0877694',
    'longtitude': '14.4196813',
    'features': 'None'
})

data_b['buildings'].append({
    'id': '1',
    'name': 'Dům - Hard rock cafe',
    'path': 'C:\\Users\\Sefci\\Documents\\_FIT\\_Bakalarka\\data_staromak\\b2',
    'latitude':   '50.0923047',
    'longtitude': '14.408226',
    'features': 'None'
})

data_b['buildings'].append({
    'id': '2',
    'name': 'U Zlaté konvice',
    'path': 'C:\\Users\\Sefci\\Documents\\_FIT\\_Bakalarka\\data_staromak\\b3',
    'latitude':   '50.0864621',
    'longtitude': '14.4185757',
    'features': 'None'
})

data_b['buildings'].append({
    'id': '3',
    'name': 'Štorchův dům, U Kamenné panny Marie',
    'path': 'C:\\Users\\Sefci\\Documents\\_FIT\\_Bakalarka\\data_staromak\\b4',
    'latitude':   '50.087185',
    'longtitude': '14.4198699',
    'features': 'None'
})

data_b['buildings'].append({
    'id': '4',
    'name': 'Pražská městská pojišťovna',
    'path': 'C:\\Users\\Sefci\\Documents\\_FIT\\_Bakalarka\\data_staromak\\b5',
    'latitude':   '50.087677',
    'longtitude': '14.4213159',
    'features': 'None'
})

with open('data.txt', 'w') as file:
    json.dump(data_b, file)
